# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Ashley Baxter"

# A description of your site for social meta tag, search engines, and feed.xml
description: "A transparent account of bootstrapping an insurance business"

# Tagline near the site title
tagline: ""

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "iamashley.co.uk"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Newsletter
  url: /newsletter/
- text: Tools I Use
  url: /tools/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Ashley Baxter"
author_bio: "Ashley is building With Jack, business insurance on a first name basis. She likes video games, photography, and her dog, Indie. Based in Glasgow, Scotland."
author_url:  "iamashley.co.uk"
author_location: "Glasgow, Scotland"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "https://withjack.co.uk"
banner_image: images/banner.jpg

# Social links in the site footer
twitter_username: "iamashley"
instagram_username: "ashleybaxter"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
