# Site setings
name: 'Ashley Baxter'
description: 'A transparent account of bootstrapping an insurance business as a solo founder. I share the lessons learned, failures and tiny wins of building With Jack.'
meta_description: 'A transparent account of bootstrapping an insurance business as a solo founder.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://iamashley.co.uk/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-52228528-1

# Author
author:
  name: 'Ashley Baxter'
  image: 'authorimage.jpg'
  description: "Hey! I'm Ashley and I'm building With Jack. I like video games, photography and my dog, Indie. Currently based in Glasgow, Scotland."
  bio: 'Ashley is founder of With Jack. She is also a photographer, speaker, and can lift heavier than you. Currently based in Glasgow, Scotland.'

# Social links
twitter: 'iamashley'
instagram: 'ashleybaxter'
linkedin: 'ashleybaxter'

# Navigation
navigation:
  - text: About
    url: /about.html

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
